# -*- coding: utf-8 -*-
"""Cronometro_Squalo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9SRZrSi-cKQe7854THkUKEM49KyFpuO
"""

import pandas as pd # Importa la librería pandas.
import time # Importa el módulo csv para crear y escribir archivos CSV.
import csv # Importa el módulo csv para crear y escribir archivos CSV.

# Función para formatear el tiempo en mm:ss.ms
def formatear_tiempo(segundos):
    minutos = int(segundos // 60) # Calcula los minutos completos.
    segundos_restantes = segundos % 60 # Calcula los segundos restantes.
    return f"{minutos:02d}:{segundos_restantes:05.2f}"  # Devuelve el tiempo formateado con 2 dígitos para minutos y 2 decimales para segundos.

# Variables iniciales
tiempo_inicio = None              # Guarda el instante en que se inicia el cronómetro (referencia global).
tiempo_vuelta_inicio = None       # Guarda el instante en que comienza la vuelta actual.
tiempo_vuelta_acumulado = 0       # Acumula el tiempo transcurrido de la vuelta actual (con pausas).
tiempo_total_acumulado = 0        # Acumula el tiempo total de todas las vueltas.
vueltas = []                      # Lista donde se guardan los tiempos de cada vuelta registrada.
en_ejecucion = False              # Booleano para indicar si el cronómetro está en marcha o pausado.

# Menú de comandos mostrados al usuario
print("== Cronómetro para registrar vueltas ==")
print("Comandos:")
print("  [1] Iniciar/Reanudar")
print("  [2] Registrar vuelta")
print("  [3] Detener (pausar)")
print("  [4] Reiniciar")
print("  [5] Salir y guardar archivo")

# Bucle principal que espera comandos del usuario hasta que decida salir.
while True:
    comando = input(">> ")  # Pide al usuario ingresar un comando.

    if comando == '1':  # Iniciar o Reanudar
        if not en_ejecucion: # Solo inicia si no está ya en ejecución.
            if tiempo_inicio is None: # Si es la primera vez, guarda el tiempo actual.
                tiempo_inicio = time.time()
            tiempo_vuelta_inicio = time.time()  # Guarda el instante en que se reinicia la vuelta.
            en_ejecucion = True # Activa el estado de ejecución.
            print("Cronómetro en marcha.")
        else:
            print("El cronómetro ya está en marcha.") # Si ya está activo, avisa al usuario.

    elif comando == '2':  # Registrar vuelta
        if en_ejecucion:
            tiempo_actual = time.time() # Obtiene el tiempo actual.
            tiempo_vuelta_acumulado += tiempo_actual - tiempo_vuelta_inicio # Suma al acumulado de la vuelta el tiempo desde el último inicio/reanudación.
            vueltas.append(tiempo_vuelta_acumulado) # Guarda la vuelta en la lista de vueltas.
            tiempo_total_acumulado += tiempo_vuelta_acumulado  # Suma el tiempo al total.
            # Muestra la vuelta actual y el total acumulado, ambos formateados.
            print(f"Vuelta {len(vueltas)}: {formatear_tiempo(tiempo_vuelta_acumulado)} | Total acumulado: {formatear_tiempo(tiempo_total_acumulado)}")
            tiempo_vuelta_acumulado = 0  # Reinicia contador de vuelta
            tiempo_vuelta_inicio = time.time()  # Nuevo inicio de vuelta
        else:
            print("Debes iniciar el cronómetro primero con '1'.")

    elif comando == '3':  # Detener (pausar)
        if en_ejecucion:
            tiempo_actual = time.time() # Obtiene el tiempo actual.
            tiempo_vuelta_acumulado += tiempo_actual - tiempo_vuelta_inicio  # Suma al acumulado de vuelta el tiempo desde el último inicio/reanudación.
            en_ejecucion = False # Cambia el estado a "detenido".
            print("Cronómetro detenido (pausa).") # Avisa al usuario.
        else:
            print("El cronómetro no está en marcha.") # Si ya está detenido, informa.

    elif comando == '4':  # Reiniciar todo
        tiempo_inicio = None # Reinicia todo desde cero.
        tiempo_vuelta_inicio = None
        tiempo_vuelta_acumulado = 0
        tiempo_total_acumulado = 0
        vueltas = []  # Vacía la lista de vueltas registradas.
        en_ejecucion = False
        print("Cronómetro reiniciado.")

    elif comando == '5':
        break # Sale del bucle principal para terminar el programa.

    else:
        print("Comando no reconocido.") # Informa si el comando no es válido.

# Guardar los resultados en un archivo CSV
if vueltas:
    nombre_archivo = "vueltas.csv" # Nombre del archivo a generar.
    with open(nombre_archivo, mode='w', newline='') as archivo: # Abre el archivo para escritura.
        escritor = csv.writer(archivo) # Crea el objeto escritor CSV.
        escritor.writerow(["Número de vuelta", "Tiempo por vuelta", "Tiempo acumulado"]) # Escribe encabezados.
        acumulado = 0 # Variable para calcular el tiempo acumulado.
        for i, vuelta in enumerate(vueltas, start=1): # Recorre todas las vueltas.
            acumulado += vuelta # Suma el tiempo de la vuelta al acumulado.
            escritor.writerow([i, formatear_tiempo(vuelta), formatear_tiempo(acumulado)]) # Escribe la fila: número de vuelta, tiempo de vuelta, tiempo total acumulado.
    print(f"\nDatos exportados exitosamente a '{nombre_archivo}'")  # Confirma la exportación.
else:
    print("No se registraron vueltas.") # Si no hay vueltas registradas, avisa.

vueltas = pd.read_csv('vueltas.csv') #Carga el archivo en un DataFrame
print(vueltas)